### ISSUE TITLE
Binary output

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/eko#60]
Since we're going to get huge output object (in particular considering huge Q2 grids, currently tested only with a single Q2) instead of dumping json/yaml file maybe it would be better to move towards a json/yaml header for a binary blob (with instructions to decode it, like "row-major, (10, 10, 100, 100), float64").

Even better: dump wiht `numpy` and the descriptions may simply tell the method to use... (check how to do it [`np.save`](https://numpy.org/doc/1.19/reference/generated/numpy.save.html#numpy.save))

**Comment by AleCandido** [comment]
Current binary **in** `yaml` it's rather good, but we definitely need to apply some kind of compression to all the binary blobs.

**Comment by AleCandido** [comment]
Compression done.

Do we want to reconsider the output format or binary-in-yaml design is fine as it is?

**Comment by felixhekhorn** [comment]
for the moment yes - maybe we can do more optimization in the future ...
