### ISSUE TITLE
Mass corrections to the DGLAP equations

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/eko#63]
sounds interesting: https://arxiv.org/pdf/2012.07154.pdf

**Comment by AleCandido** [comment]
@felixhekhorn are we realistically interested in this?

I have the feeling we might start collecting this and a few others somewhere else (e.g. a wiki page), and leave the issue tracker for things that really scheduled in the short-medium term.
What do you think?

**Comment by felixhekhorn** [comment]
I agree - if ever this is really a long term feature ...

and, if possible, let's aim to not keep issues and PR alive that are stale or ancient ... the wiki page can e.g. contain just a link to here ...

**Comment by felixhekhorn** [comment]
https://github.com/N3PDF/eko/wiki/List-of-Possible-Future-Features

**Comment by giacomomagni** [comment]
This other two references can be useful if we want to address this at some point: 
* https://inspirehep.net/literature/1242455
* https://inspirehep.net/literature/2136620
