### ISSUE TITLE
Renaming output does not work

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/eko#81]
**Describe the bug**
Renaming the output file leads to the thing being unusable

**To Reproduce**
1. save an output to `a.tar`
2. rename `a.tar` to `b.tar`
3. try to load `b.tar`
4. See error: "... metadata.yaml not found ..." 

**Expected behavior**
it should still work, since EKOs are expensive we want to be able to reuse them (if e.g. my mistake the name was miscomputed)

**Additional context**
this is coming from [here](https://github.com/N3PDF/eko/blob/470d892e2ad4ec589a8f6ca12185f19a6fc8c69c/src/eko/output.py#L501)
maybe, if the things fail we should check if there is one directory and choose that one

---

- [ ] add unit test for the future: dump -> rename -> attempt to load

**Comment by AleCandido** [comment]
I'd say it's more coming from here:
https://github.com/N3PDF/eko/blob/470d892e2ad4ec589a8f6ca12185f19a6fc8c69c/src/eko/output.py#L406 
and then:
https://github.com/N3PDF/eko/blob/470d892e2ad4ec589a8f6ca12185f19a6fc8c69c/src/eko/output.py#L501
is consequential.

I'll fix it this afternoon.

**Comment by felixhekhorn** [comment]
it's even fine as a default, this should be a second option, I think ...

**Comment by AleCandido** [comment]
If this is preventing renaming, and we can avoid, then let's avoid :)

**Comment by AleCandido** [comment]
Actually, I don't need to rely on any external name, since there is a single folder inside the tar.

Now I'm simply iterating inside the content, thus I found the inner folder, whatever its name is, and I load its content.

**Comment by AleCandido** [comment]
Now I even succeeded in testing the implementation (before I tested the trick in isolation, but it was not enough).

Before closing, maybe we should write a regression (in unit tests, of course), to make sure it will work even in future (dump -> renaming -> loading).

**Comment by felixhekhorn** [comment]
> Before closing, maybe we should write a regression (in unit tests, of course), to make sure it will work even in future (dump -> renaming -> loading).

done in https://github.com/N3PDF/eko/commit/c657c047c2eb43c7fa6bb99ec3ced3349dabc4e9 - this fails in https://github.com/N3PDF/eko/commit/4f963e889d13468a1e8eabbc8290799659975e88

**Comment by AleCandido** [comment]
Thank you very much @felixhekhorn
