### ISSUE TITLE
Call anomalous mass dimension \gamma_m

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/eko#84]
To avoid confusion, let's call he anomalous mass dimension `\gamma_m` (in contrast to the anomalous PDF dimension that we keep at `\gamma`). This has to be changed:
- in the [docs](https://eko.readthedocs.io/en/develop/theory/pQCD.html)
- in the [paper](https://github.com/N3PDF/papers/blob/e20c79f90724d66251efe416c7c32a80b01668e4/eko/sections/phenomenology/msbar-masses.tex)
- in the code (if used anywhere ... I think, gamma function and anomalous dimension are fine as names ...)

**Comment by giacomomagni** [comment]
Okay I agree. Will take care of fixing this.

**Comment by giacomomagni** [comment]
I noticed that we do have all the ingredients for easily adding also the N3LO msbar evolution. Shall I open a PR?

**Comment by felixhekhorn** [comment]
I guess later we want to go full N3LO - so I'd say go ahead ...
