### ISSUE TITLE
Evolved PDF object

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/eko#93]
At the moment, the only output of `eko` is the operator itself, and for the main package is even fine.

In order to have a usable evolved and interpolated object, you need to build/load the operator, apply it, dump the PDF set in lhapdf format, and load again with lhapdf.

It is nice to have lhapdf interface, but I'd say that it should not be mandatory to use an evolved set.

### Proposal

Let's make:
1. a shallow clone of `lhapdf.PDFset` (more or less as we are doing for ToyLH in `banana`)
2. a function that takes a input PDF, an operator, and creates this object (so a constructor for the object above)

The benefit will be to have people being able to use `eko` alone, without the need for any extra non-trivial dependency.

Of course, an extra method could be:
- dump the object in lhapdf format

but this should be considerably simple, reusing the one that has been already implemented (the class should be simply retain all the information that is currently consumed to dump).

**Comment by giacomomagni** [comment]
Maybe @AleCandido  we can close this, since we have `ekobox`  now ?

**Comment by felixhekhorn** [comment]
I guess @AleCandido was thinking about to explicitly avoid lhapdf, but I wonder if that is truly needed - I'd say we just rely on the standard tools instead of reinventing the wheel ...

**Comment by AleCandido** [comment]
Agreed. I guess we have something close to it, and if not, we're not really interested in for the time being.

I'll close, and we'll worry again only if we'll need it for something.
