### ISSUE TITLE
Minimize the amount of initial imports

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/eko#94]
**Motivation**: As soon as you install `eko`, you'll need to wait a while on first import. This is needed for the `eko` *application*, but unnecessary and completely counter-intuitive for the `eko` library.

At the moment importing `eko` means importing `eko.runner`, and also `eko.output`.

Then, as it makes sense, importing runner means importing everything (see [dependency graph](https://eko.readthedocs.io/en/latest/code/Dependency.html)).

### How to improve

From my point of view:
- there is no way to improve on `eko.runner`: it's quite intuitive that uses all (or almost all) of the library
- but I'd say that we should not wait on the compilation of all the anomalous dimensions and so on, if you only need interpolation or strong coupling (or even masses, basis rotation, ...)

In particular, having to wait every time you install anew it's already a bit unpleasant in `yadism`, but much more in `banana` or `runcards`.

### In practice

I'd say we just need to:
- [ ] shuffle back `run_dglap` inside `eko.runner`
- [ ] at this point we can keep the main `__init__.py` just for the version (no need for a separate module)
- [ ] update related docs

**Comment by AleCandido** [comment]
I believe we don't need this any longer, because of:
- mainly the `numba` rearrangement
- and the forthcoming runner-less structure (in which runner will be optional, and thus by default importing much less)

Can we close this? @giacomomagni @felixhekhorn

**Comment by giacomomagni** [comment]
okay, fine

**Comment by felixhekhorn** [comment]
Agreed
